name: slim-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - tskit
  - gcc_linux-64
  - gxx_linux-64
  - make
  - cmake
  - eigen
  - gsl
  - git
  - pip
  - pip:
      - pyslim
      - msprime
