#!/bin/bash
set -e

echo "Installing SLiM from source..."

# Download SLiM 4.2
wget -q https://github.com/MesserLab/SLiM/releases/download/v4.2/SLiM-4.2.tar.gz
tar -xzf SLiM-4.2.tar.gz
cd SLiM-4.2

# Build
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j2

# Install slim binary
cp slim /usr/local/bin/
cd ../..

# Clean up
rm -rf SLiM-4.2 SLiM-4.2.tar.gz

echo "SLiM installed successfully!"
slim -version
